jquery/turnitin_module.js, lib.php
Fix rubric view icon and link.
=> Fix rubric view icon and link.

jquery/turnitin_module.js
Fix for duplication of rubric on second open.
=> Fix for duplication of rubric on second open.

turnitinplugin_view.class.php
Initialise shared rubrics before reading class.
=> Initialise shared rubrics before reading class.

lib.php
=> Support for PHP 5.3

CHANGELOG.md
=> Release v2015040111

lib.php
Output success message in cron.
=> Output success message in cron.

lib.php
I think this re-declaration was the source of the problematic error message.
=> removed un-necessary re-declaration of variable .

ajax.php, extras.php, lib.php
Separate pull request due to merge conflicts
=> Show more errors in cron output and allow submissions to flow

lib.php
No error was generated in my test.
=> Referenced variable $turnitinassignid in message text.

lib.php
Improve cron errors for failed user creation.
=> Improve cron errors for failed user creation.

lib.php
Fix PP pending issue on deleted text submissions.
=> Fix PP pending issue on deleted text submissions.

lib.php
PP Pending issue for temp file creation error.
=> PP Pending issue for temp file creation error.

lib.php
Fix for disappearing EULA acceptance link in PP.
=> Fix for disappearing EULA acceptance link in PP.

styles.css
=> Fix double TII icon issue

lang/en/plagiarism_turnitin.php, lib.php
Made the message less apocalyptic and linked it to an error code so that the student has a chance of knowing what went wrong.
=> Reason for deletion

lang/en/plagiarism_turnitin.php
Fix language string - "from from" changed to "from"
=> Fix language string

ajax.php
Add activity log for EULA acceptance.
=> Add activity log for EULA acceptance.

jquery/turnitin_module.js
=> Fix EULA modal duplication.

CHANGELOG.md
=> Staged for release.

settings.php
This is causing problems with the display of the data dump for a lot of users.
=> Change recordset back to records

lib.php
Implementing @danmarsden's PR https://github.com/turnitin/moodle-plagiarism_turnitin/pull/136 to ensure assignment defaults are applied to the develop branch.
=> Ensure assignment default settings are applied (Thanks to @dmarsden)

lib.php
=> Fix error language string.

lib.php
Resubmit for development branch
=> Add check for file contents - Resubmit

lib.php
Fix edge case user not found pending issue.
=> Fix edge case user not found pending issue.

CHANGELOG.md, version.php
Release notes and version number.
=> Release notes and version number.

lib.php
Use default settings when editing an assignment created without Turnitin enabled.
=> INT-7085 - Use default settings when editing an assignment created without Turnitin enabled.

db/install.xml, db/upgrade.php
Removed unused database columns in plagiarism_turnitin_files leftover from the DM plugin.
=> Removed unused columns leftover from the DM plugin.

lang/ar/plagiarism_turnitin.php, lang/cs/plagiarism_turnitin.php, lang/de/plagiarism_turnitin.php, lang/es/plagiarism_turnitin.php, lang/fi/plagiarism_turnitin.php, lang/fr/plagiarism_turnitin.php, lang/it/plagiarism_turnitin.php, lang/ja/plagiarism_turnitin.php, lang/ko/plagiarism_turnitin.php, lang/nl/plagiarism_turnitin.php, lang/pl/plagiarism_turnitin.php, lang/pt_br/plagiarism_turnitin.php, lang/ro/plagiarism_turnitin.php, lang/ru/plagiarism_turnitin.php, lang/sv/plagiarism_turnitin.php, lang/tr/plagiarism_turnitin.php, lang/vi/plagiarism_turnitin.php, lang/zh_hans/plagiarism_turnitin.php, lang/zh_tw/plagiarism_turnitin.php
=> INT-7521 - Update language strings.

lib.php
We've found some issues with our event changes on our develop branch during QA. This pull request fixes them.
=> Event fixes for our develop branch

db/upgrade.php, version.php
Remove old/unused event on PP upgrade.
=> Remove old/unused event on PP upgrade.

lib.php
Change for exclude matches variable setting.
=> Change for exclude matches variable setting.

CHANGELOG.md, version.php
=> Release notes v2017012501

CHANGELOG.md, db/upgrade.php, version.php
=> Release 2017013101

lib.php
This will make the submitter value the same as userid if it is not present and account for any potential cases where userid is not set. 
This should fix https://github.com/turnitin/moodle-plagiarism_turnitin/issues/224.
=> Fix empty submitter value and account for a potential empty userid.

lang/en/plagiarism_turnitin.php, lib.php
Account for submissions where there is no submissiontype.
Check file and forum posts exist before submitting.
Minor refactor of saving errored submissions.
=> Fix cron sticking issues

lib.php
added code to stop coursework from using update_grade()
=> Cron fix coursework

lib.php
I think this should fix it - I don't like the way this function looks all that much but this retains the existing logic. (just re-running all the behat tests on our systems - will report back if it's still failing.)
=> Fixes #179 Behat test failure.

jquery/turnitin_module.js, jquery/turnitin_module_pre29.js, lib.php
This will fix the problem in PR 200 where the TFS launchers aren't launching in Moodle's grader interface.
=> Fix TFS launchers in Moodle's Grader interface

CHANGELOG.md, lib.php
Fix error in 3.3 on the new bulk completion edit page.
=> Fix error in 3.3 on the new bulk completion edit page.

lang/en/plagiarism_turnitin.php, lib.php
Fix issue where the cron would fail on a queued submission if the submission belonged to an assignment on a course which has been deleted.
=> Fix cron stuck problem when course has been deleted.

CHANGELOG.md, version.php
=> Release 2017070301

CHANGELOG.md, version.php
=> Release v2017080901

CHANGELOG.md, jquery/turnitin_module.js, jquery/turnitin_module_post29.js, lang/en/plagiarism_turnitin.php, lib.php, version.php
=> Develop to master

CHANGELOG.md
=> Release note addition.

tests/lib_test.php
=> Removing whitespace.

db/access.php, lib.php, version.php
Fix group submission grading when submitting on behalf of a student.
=> Fix group submission grading when submitting on behalf of a student.

CHANGELOG.md
=> Release 2017112302

version.php
=> Version number

lib.php
Hi, here is a patch for https://github.com/turnitin/moodle-plagiarism_turnitin/issues/288
All it does is:
1. Only saves a different submitter from the author when the submission is probably being edited by a tutor, rather than submitted by a student.
2. Looks up the user who made the latest group submission explicitly in get_links(), rather than inferring it from the group membership.
I've tested it pretty thoroughly and as far as I can see it's sound, but it would be good if someone could confirm that there are no scenarios where the queries on L705 and L811 could return a different record.
There's one outstanding edge case that it doesn't cover, which is where someone has the 'mod/assign:editothersubmission' capability on an assignment in Moodle, but Turnitin thinks they're a student. I …
=> Fix group submissions

CHANGELOG.md, version.php
=> Release 2018011602

lang/ar/plagiarism_turnitin.php, lang/cs/plagiarism_turnitin.php, lang/de/plagiarism_turnitin.php, lang/en/plagiarism_turnitin.php, lang/es/plagiarism_turnitin.php, lang/fi/plagiarism_turnitin.php, lang/fr/plagiarism_turnitin.php, lang/it/plagiarism_turnitin.php, lang/ja/plagiarism_turnitin.php, lang/ko/plagiarism_turnitin.php, lang/nl/plagiarism_turnitin.php, lang/pl/plagiarism_turnitin.php, lang/pt_br/plagiarism_turnitin.php, lang/ro/plagiarism_turnitin.php, lang/ru/plagiarism_turnitin.php, lang/sv/plagiarism_turnitin.php, lang/tr/plagiarism_turnitin.php, lang/vi/plagiarism_turnitin.php, lang/zh_hans/plagiarism_turnitin.php, lang/zh_tw/plagiarism_turnitin.php
Adding missing language strings
=> Adding missing language strings

lib.php, version.php
=> Implement temp file logic

classes/privacy/provider.php, lang/en/plagiarism_turnitin.php, tests/lib_test.php, tests/privacy/provider_test.php, version.php
=> GDPR implementation

classes/privacy/provider.php, tests/privacy/provider_test.php
Privacy test fixes plus query fix
=> Privacy test fixes plus query fix

CHANGELOG.md, version.php
=> Release 2018052401

classes/privacy/provider.php
Fix undefined index for export.
=> Fix undefined index for export.

ajax.php, classes/turnitin_view.class.php, extras.php, lib.php, settings.php
- Move view class
- Add launch method
=> Move view class and add launch method

ajax.php, classes/turnitin_comms.class.php, classes/turnitin_view.class.php
- Add PeerMark and QM launches to turnitin_view class
=> Add peermark launch to turnitin_view

classes/turnitin_comms.class.php, classes/turnitin_view.class.php, extras.php, lib.php, settings.php, version.php
Reproduce output header and print error
=> Reproduce output header and print error

db/install.xml, db/upgrade.php, lib.php, version.php
=> implement PeerMark table

classes/modules/turnitin_assign.class.php, lib.php, tests/modules/turnitin_assign_test.php, version.php
Fix duplicate submissions in PP Turnitin
=> Fix duplicate submissions in PP Turnitin

CHANGELOG.md, tests/privacy/provider_test.php, version.php
Release notes for release 2018062601
=> Release notes for release 2018062601

ajax.php, classes/turnitin_user.class.php, classes/turnitin_view.class.php, extras.php, lib.php
Ensure the PP user class is called and not V2's.
Also fixes the call to the comms class. (as a side note it is correct that this calls V2 as moving that across is a separate ticket and needs to be done last)
=> Ensure the PP user class is called and not V2's

lib.php, tests/lib_test.php
Check if property exists before using.
=> Check if property exists before using.

classes/turnitin_view.class.php, lang/ar/plagiarism_turnitin.php, lang/cs/plagiarism_turnitin.php, lang/de/plagiarism_turnitin.php, lang/en/plagiarism_turnitin.php, lang/es/plagiarism_turnitin.php, lang/fi/plagiarism_turnitin.php, lang/fr/plagiarism_turnitin.php, lang/it/plagiarism_turnitin.php, lang/ja/plagiarism_turnitin.php, lang/ko/plagiarism_turnitin.php, lang/nl/plagiarism_turnitin.php, lang/pl/plagiarism_turnitin.php, lang/pt_br/plagiarism_turnitin.php, lang/ro/plagiarism_turnitin.php, lang/ru/plagiarism_turnitin.php, lang/sv/plagiarism_turnitin.php, lang/tr/plagiarism_turnitin.php, lang/vi/plagiarism_turnitin.php, lang/zh_hans/plagiarism_turnitin.php, lang/zh_tw/plagiarism_turnitin.php, lib.php
=> Copy any remaining strings.

ajax.php, extras.php, settings.php
=> Replace config with old path

classes/forms/turnitin_setupform.class.php
- Adding support for QA urls from config
- Changing URLs to be base URL instead of English strings
=> Add support for QA urls

settings.php
Display correct current tab on logs.
=> Display correct current tab on logs.

db/upgrade.php, lib.php, tests/behat/assignment_multiple_files.feature, tests/behat/behat_plagiarism_turnitin.php, tests/fixtures/testfile2.txt, version.php
This pull request fixes a regression in the previous version which prevented multiple file submissions from being queued to Turnitin.
Split branch.
=> Fixing regression for multiple file uploads in split branch.

lib.php, tests/behat/assignment_multiple_files.feature, tests/behat/behat_plagiarism_turnitin.php, tests/fixtures/testfile2.txt, version.php
This pull request fixes a regression in the previous version which prevented multiple file submissions from being queued to Turnitin.
=> Fix multiple file submit regression

lang/en/plagiarism_turnitin.php, lib.php
Porting fixes from main branch to split branch
=> INT-8576 Cron gets stuck if report scores cannot be updated.

lib.php
Update reference to V2 JS name.
=> Update reference to V2 JS name.

lib.php
Revert prepared statement change.
=> Revert prepared statement change.

lib.php
Revert prepared statement change.
=> Revert prepared statement change - split

classes/turnitin_view.class.php, jquery/turnitin_module.js
Fix rubric option so that rubrics are saved - split branch.
=> Fix rubric option so that rubrics are saved - split branch.

CHANGELOG.md, classes/privacy/provider.php, version.php
Releasing Moodle PP v2018082802
=> Releasing Moodle PP v2018082802

tests/behat/assignment.feature, tests/behat/assignment_any_file_type.feature, tests/behat/assignment_drafts.feature, tests/behat/assignment_groups.feature, tests/behat/assignment_multiple_files.feature, tests/behat/assignment_resubmission.feature, tests/behat/eula.feature, tests/behat/forum.feature, tests/behat/installed.feature, tests/behat/pseudo_submission.feature, tests/behat/workshop.feature
=> Removing deprecated step.

tests/behat/assignment.feature, tests/behat/assignment_any_file_type.feature, tests/behat/assignment_drafts.feature, tests/behat/assignment_groups.feature, tests/behat/assignment_multiple_files.feature, tests/behat/assignment_resubmission.feature, tests/behat/eula.feature, tests/behat/forum.feature, tests/behat/installed.feature, tests/behat/pseudo_submission.feature, tests/behat/workshop.feature
=> Further deprecations

tests/behat/forum.feature
=> Forum test fixes

tests/behat/assignment.feature, tests/behat/assignment_any_file_type.feature, tests/behat/assignment_drafts.feature, tests/behat/assignment_groups.feature, tests/behat/assignment_multiple_files.feature, tests/behat/assignment_resubmission.feature, tests/behat/behat_plagiarism_turnitin.php, tests/behat/eula.feature, tests/behat/forum.feature, tests/behat/pseudo_submission.feature, tests/behat/workshop.feature
Change the way EULAs are handled in behat.
=> Change the way EULAs are handled in behat.

CHANGELOG.md, lib.php, version.php
=> Release 2018102901

CHANGELOG.md, classes/digitalreceipt/pp_receipt_message.php, classes/privacy/provider.php, lib.php, version.php
Develop to master for release 2018102901
=> Develop to master for release 2018102901

lib.php
Fix undefined index for group submissions.
Same code changes as #388 minus the behat which only exists in the split branch.
=> Fix undefined index for group submissions.

lib.php, tests/behat/assignment_groups.feature
Fix undefined index for group submissions.
=> Remove undefined index group submission

db/upgrade.php, lang/ar/plagiarism_turnitin.php, lang/cs/plagiarism_turnitin.php, lang/de/plagiarism_turnitin.php, lang/en/plagiarism_turnitin.php, lang/es/plagiarism_turnitin.php, lang/fi/plagiarism_turnitin.php, lang/fr/plagiarism_turnitin.php, lang/it/plagiarism_turnitin.php, lang/ja/plagiarism_turnitin.php, lang/ko/plagiarism_turnitin.php, lang/nl/plagiarism_turnitin.php, lang/pl/plagiarism_turnitin.php, lang/pt_br/plagiarism_turnitin.php, lang/ro/plagiarism_turnitin.php, lang/ru/plagiarism_turnitin.php, lang/sv/plagiarism_turnitin.php, lang/tr/plagiarism_turnitin.php, lang/vi/plagiarism_turnitin.php, lang/zh_hans/plagiarism_turnitin.php, lang/zh_tw/plagiarism_turnitin.php, lib.php, version.php
$moduledata->teamsubmission is always set for mod assign, but only for mod assign. So the logic has been moved to be within the mod assign check only.
I've also added a string which was missing from this branch.
=> Remove undefined index issue for behats

db/upgrade.php, lang/ar/plagiarism_turnitin.php, lang/cs/plagiarism_turnitin.php, lang/de/plagiarism_turnitin.php, lang/en/plagiarism_turnitin.php, lang/es/plagiarism_turnitin.php, lang/fi/plagiarism_turnitin.php, lang/fr/plagiarism_turnitin.php, lang/it/plagiarism_turnitin.php, lang/ja/plagiarism_turnitin.php, lang/ko/plagiarism_turnitin.php, lang/nl/plagiarism_turnitin.php, lang/pl/plagiarism_turnitin.php, lang/pt_br/plagiarism_turnitin.php, lang/ro/plagiarism_turnitin.php, lang/ru/plagiarism_turnitin.php, lang/sv/plagiarism_turnitin.php, lang/tr/plagiarism_turnitin.php, lang/vi/plagiarism_turnitin.php, lang/zh_hans/plagiarism_turnitin.php, lang/zh_tw/plagiarism_turnitin.php, lib.php, version.php
=> Remove resubmission message from forum

lib.php, turnitinplugin_view.class.php
Don't run the cron tasks if the plug can't connect to Turnitin.
=> Don't run the cron tasks if the plug can't connect to Turnitin.

db/upgrade.php, version.php
Reset existing error code 13s on plugin upgrade.
=> Reset existing error code 13s on plugin upgrade.

CHANGELOG.md, db/upgrade.php, version.php
=> Release v2019031301

classes/privacy/provider.php, lang/en/plagiarism_turnitin.php, tests/privacy/provider_test.php
Adding privacy provider line about the content we send.
=> Adding privacy provider line about the content we send.

CHANGELOG.md, db/upgrade.php, version.php
=> Release v2019050201

tests/behat/assignment_any_file_type.feature, tests/behat/assignment_drafts.feature, tests/behat/assignment_groups.feature, tests/behat/assignment_resubmission.feature, tests/behat/eula.feature, tests/behat/installed.feature, tests/behat/pseudo_submission.feature
We've had reports of behats failing, I can't reproduce but have modified the features as requested anyway
=> Modified behat features and remove empty feature file

CHANGELOG.md, version.php
=> Release v2019060601

CHANGELOG.md
Develop to master release note addition
=> Develop to master release note addition

CHANGELOG.md, db/upgrade.php, version.php
Develop to master for v2019062501
=> Develop to master for v2019062501

ajax.php, classes/digitalreceipt/pp_receipt_message.php, classes/forms/turnitin_form.class.php, classes/modules/turnitin_assign.class.php, classes/turnitin_class.class.php, lib.php, tests/behat/behat_plagiarism_turnitin.php
=> Fix some minor codechecker violations

tests/behat/behat_plagiarism_turnitin.php
Updated method the_following_exist to the the_following_entities_exist in behat_plagarism_turnitin class
=> Int 13718 fix automation test

lib.php
Prevent error code 13 hiding submissions when grading.
Fix for https://github.com/turnitin/moodle-plagiarism_turnitin/issues/487
=> Prevent error code 13 hiding submissions when grading

CHANGELOG.md, tests/behat/assignment.feature, tests/behat/assignment_any_file_type.feature, tests/behat/assignment_drafts.feature, tests/behat/assignment_groups.feature, tests/behat/assignment_multiple_files.feature, tests/behat/assignment_resubmission.feature, tests/behat/eula.feature, tests/behat/forum.feature, tests/behat/installed.feature, tests/behat/pseudo_submission.feature, tests/behat/workshop.feature, version.php
=> Release 2019121701

classes/privacy/provider.php, tests/privacy/provider_test.php
This fixes the issue with the get_contexts_for_userid() method in #394.
=> Fix get contexts for userid

classes/privacy/provider.php, tests/privacy/provider_test.php
This fixes the issue with delete_plagiarism_for_user() raised in #394
=> Fix delete_plagiarism_for_context()

lib.php
Reverts turnitin/moodle-plagiarism_turnitin#464
=> Revert "Clicking similarity score triggers N Ajax requests"

lib.php
Reverts turnitin/moodle-plagiarism_turnitin#493
=> Revert "Revert "Clicking similarity score triggers N Ajax requests""

lib.php
Reverts turnitin/moodle-plagiarism_turnitin#529
=> Revert "refactor if"

db/install.xml, db/upgrade.php, version.php
Hi everyone - I've closed all the related PRs and Issues and want to keep everything unified under this one request.
=> Fix db inconsistencies

tests/classes/turnitin_assignment_class_test.php, tests/classes/turnitin_user_class_test.php, tests/modules/turnitin_assign_test.php, tests/modules/turnitin_forum_test.php
Reverts turnitin/moodle-plagiarism_turnitin#571
=> Revert "update tests to support 3.10"

lib.php
Added sort order in order to process older request.
#556
=> Issue#556 Add sort order by lastmodified.

ajax.php, classes/turnitin_comms.class.php, lib.php
Also, handle test connection after install when no config has been set
=> Don't overwrite Moodle grades if there is no grade in TFS

lib.php
=> Only submit essay questions

lang/en/plagiarism_turnitin.php, lib.php
=> Fix failure to submit queued items when an item's attempt is missing.

db/upgrade.php, version.php
This is to fix #517 (develop branch)
=> Set userid and courseid columns to be NOT NULL (develop branch)

classes/privacy/provider.php
=> Add core_userlist_provider

vendor/Integrations/phpsdk-package/src/Soap.php
=> fixed correct return type for soap::__doRequest() 

lib.php
=> Do not use settings form for Moodle 4.3 bulk completion as well

README.md
This reference is not needed any more.
=> Remove asterisk in quiz reference in README.md.

vendor/Integrations/phpsdk-package/src/OAuthSimple.php
Omit PHP Deprecated: Creation of dynamic property warning.
=> Adding OAuthSimple.php properties resolves #710.

classes/modules/turnitin_quiz.class.php
=> Fix unit test - Resolves issue #659

classes/modules/turnitin_quiz.class.php
Reverts turnitin/moodle-plagiarism_turnitin#660
=> Revert "Fix unit test - Resolves issue #659"

classes/observer.php, db/events.php, lib.php, version.php
Duplicate of #730, except with a few minor changes
=> Add submission removed observer

dbexport.php
This has been deprecated for a while, and was removed in Moodle 4.4
=> Replace download_as_dataformat

lib.php, styles.css
We should update the colours we use for similarity scores to reflect this: https://guides.turnitin.com/hc/en-us/articles/23435833938701-Understanding-the-Similarity-Score
=> Update similarity score colours

vendor/Integrations/phpsdk-package/src/Soap.php
=> Change $one_way to boolean

lib.php
Caching module data and using INNER JOIN
=> More database optimisation

classes/hook_callbacks.php, db/hooks.php
=> 770 Add install state check for Hooks API

classes/hook_callbacks.php
The current code is causing a core unit test failure (#844)
=> Using $PAGE->pagetype to check if on quiz page

tests/lib_test.php
Fix the issue https://github.com/turnitin/moodle-plagiarism_turnitin/issues/872
=> Issue #872 Fix phpunit error for Moodle 4.1

lib.php
To facilitate assignment copy the post date must be after the due date.
=> Ensure post date is at least 1 sec after start date
