- lib.php
- settings.php
- turnitinplugin_view.class.php
When viewing the errors report - for large institutions you can have a
long list of errors - when typically you're only interested in recent
ones.
This change adds a paging bar to the top and bottom of the report and
has it display 100 records per page.
The underlying record lookup is also adjusted to only load the 100
records related to the page - instead of ALL of them, reducing the
memory footprint considerably.
> Add paging bar to errors report

- settings.php
When accessing 'viewreport' or 'savereport' from the settings page, the
report loads ALL the records from the config and files tables.
For large datasets, this is ALOT of data and fills up memory fast. By
using get_recordset instead, the entire dataset isn't loaded into memory
at once, avoiding an out-of-memory error on these pages.
> Load table data with recordset to avoid memory issues

- lib.php
- Set `$plagiarismsettings` using line borrowed from another function, feeding in `$cm` as parameter.
- Tidied up the code producing the comment
> rectified bug of unset variable

- lib.php
Grademark icon no longer visible to student if anonymous/blind is on.
> Grademark icon no longer visible to student if anonymous/blind is on.

- db/install.xml
- db/upgrade.php
- lib.php
- Created new field in database to signify whether a submission needs to have the OR re-synced after the expiration of a due date.
- Updated upgrade.php
- field values:
- 0 => default, submission existed before this was all rolled out, or the due date has not yet passed.
- 1 => assignment OR report needs to be re-synced.
- 2 => assignment OR has already been re-synced.
- Upon setting the due date for an assignment, if that due date is in the future, then the duedate_report_refresh flag for each submission is set to 1 wherever it was previously 2. Otherwise, no change. 
- When cron runs, each submission subject to a due date that passed within the last twenty four hours will have the duedate_report_refresh flag set from 0 to 1.
- Once the assignments have had their OR refreshed, the flag …
> Duedate update

- db/install.xml
- lib.php
- settings.php
when DB foreign key enable we can't use 0 as index we need to use null instead.
In cron run sometimes there is error about missing index.
> Add foreign key support and cron error fix

- lang/en/plagiarism_turnitin.php
For some reason these error strings were missing from the language string file but are referenced from the plugin. This pull request adds them.
> Add missing error language strings.

- jquery/turnitin_module.js
When calling colorbox directly on the EULA link, it doesn't always open
in an iframe if the student has previously declined the EULA - often it
will load the form inline, resulting in the browser being redirected to
the EULA on a blank page on the TII site instead of displaying on top of
the Moodle page.  This means that the user gets "stuck" on the TII site -
they're not returned to Moodle after either accepting or declining.
This fixes issue #89.
> Wrap colorbox in a click handler for EULA link

- lib.php
This fix prevents grades from being passed to gradebook before identities have been revealed when blind marking is on.
> Prevent grades being passed to gradebook before identities are revealed

- lib.php
- tests/turnitin_test.php
Hi, pulling request again based on 'develop'.
When I run core Moodle 31 PHPUnit tests, one of them fails if I have this plugin installed.
I've isolated the problem in the lib, where it finds the supported modules based on the file (classes/modules) system then tries to fetch the ID in the database.
Because it cannot find the module in the DB (returns false), if fails when trying go get the $module->id.
I wrote a test reproducing the behaviour and a proposed solution; however, someone who has better understanding of this plugin could propose a better solution.
Cheers,
Daniel
> Issue #179 - PHPUnit test failing with Moodle 31

- lib.php
The error message language string was not being set for files greater than 40mb.
> Fix error code for 40mb file.

- lib.php
A call to mod/forum/post.php may trigger a print_disclosure() for all plagiarism plugins.
If the TII server is slow (or there is a timeout), the page becomes very slow even when turn it in is not needed.
This fix: print_disclosure() now only checks the connection when it is needed.
> (develop) Fixes Issue #194 - Turnitin slows mod/forum/post.php even when TII is not enabled for that mod.

- lib.php
A Moodle upgrade will fail If this plugin is installed on older versions.
See MDL-46122, lib/pluginlib.php was removed in Moodle 2.9.
> Fixes issue #219 - added checking if pluginlib.php file exists.

- lib.php
This function is used from outside the class its in during cron, so we
can't have it private till thats fixed up.
Without this change, a submission triggering that call can cause Moodle
cron to get blocked.
> Keep delete_tii_submission public till its no longer called externally

- lib.php
Currently the course data is still fetched (even if it isn't used), and
the addition of the settings form elements is skipped only for one type
of bulk completion editing form (not the default completion form).
> plagiarism_turnitin: Don't even get course data for any bulk completion

- classes/modules/turnitin_assign.class.php
- lib.php
- tests/modules/turnitin_assign_test.php
Only resubmits to Turnitin if:
- Max files is 1 for file submissions
- Attempts are off
- Report Gen Speed is > 0
Please ignore the indentation errors in lib.php (IDE changes), I'll fix these in a separate PR once this has passed Code Review.
> Handle resubmissions correctly if only 1 file is allowed to be submitted

- turnitinplugin_view.class.php
Removing rubric dropdown population from settings page as it's done via Ajax anyway and we can't categorise the options as we'd like using Moodle's libraries. This is now consistent with the native website behaviour.
> Remove rubric population from settings page

- lib.php
The "resubmit to Turnitin" functionality doesn't work correctly after #289. This patch fixes it.
> Check capability for submitter not current user

- classes/digitalreceipt/pp_receipt_message.php
- lib.php
Fixed an issue where send_queued_files task would fail.
Changed depecated stdClass() to new \core\message\message() for event data.
Fixed an issue where the $cm parameter was not being passed in during a text submission.
> Moodle 35 fixes

- backup/moodle2/backup_plagiarism_turnitin_plugin.class.php
- backup/moodle2/restore_plagiarism_turnitin_plugin.class.php
- classes/turnitin_class.class.php
- db/install.xml
- db/upgrade.php
- lib.php
- version.php
This pull request replaces the broken #316.
Note: Until the assignment logic is moved across then this will not remove all dependencies.
This is because when a new course is created in Moodle, it will only be created in the database tables when the first assignment/submission is made and the cron runs.
What this means is that the cron will call get_course_data, which in turn calls create_tii_course if a course doesn't exist. This then calls a function of the same name in turnitintooltwo_assignment class which inserts into turnitintooltwo_courses.
What does change in this PR is we now have a courses table with the data migrated across during a plugin upgrade, and all references to turnitintooltwo_courses have been removed with the new plagiarism_turnitin_courses table.
course_type field is …
> Feature remove class dependency

- classes/forms/turnitin_defaultsettingsform.class.php
- classes/forms/turnitin_setupform.class.php
- extras.php
- settings.php
Fix errors when accessing default settings due to the relocation of the view class. It was being called by a class in Moodle Direct v2 - This dependency has been removed but the redundant code can't be removed from V2 until we release this.
Also renamed the setup form to be consistent with other classes.
> Fix default settings errors and rename the plugin settings form.

- classes/digitalreceipt/pp_receipt_message.php
This fixes the issue where the scheduled task `send queued files` would fail in Moodle 3.1 and below due to an invalid courseid parameter.
> Removing courseid parameter for Moodle 3.1 and below

- classes/turnitin_user.class.php
- lang/ar/plagiarism_turnitin.php
- lang/cs/plagiarism_turnitin.php
- lang/de/plagiarism_turnitin.php
- lang/en/plagiarism_turnitin.php
- lang/es/plagiarism_turnitin.php
- lang/fi/plagiarism_turnitin.php
- lang/fr/plagiarism_turnitin.php
- lang/it/plagiarism_turnitin.php
- lang/ja/plagiarism_turnitin.php
- lang/ko/plagiarism_turnitin.php
- lang/nl/plagiarism_turnitin.php
- lang/pl/plagiarism_turnitin.php
- lang/pt_br/plagiarism_turnitin.php
- lang/ro/plagiarism_turnitin.php
- lang/ru/plagiarism_turnitin.php
- lang/sv/plagiarism_turnitin.php
- lang/tr/plagiarism_turnitin.php
- lang/vi/plagiarism_turnitin.php
- lang/zh_hans/plagiarism_turnitin.php
- lang/zh_tw/plagiarism_turnitin.php
- lib.php
- tests/behat/assignment.feature
- tests/behat/behat_plagiarism_turnitin.php
- tests/behat/installed.feature
This pull request fixes the behat tests for this branch. The tests were built as part of develop and were calling V2 settings however this plugin has its own settings now that needed to be called.
Also fixed a findUser issue that was created as a result of the new SDK implementation, and added a language string which was missing for an error message.
> Fix behat tests and add missing string

- tests/behat/assignment.feature
- tests/behat/assignment_any_file_type.feature
- tests/behat/assignment_drafts.feature
- tests/behat/assignment_groups.feature
- tests/behat/assignment_multiple_files.feature
- tests/behat/assignment_resubmission.feature
- tests/behat/behat_plagiarism_turnitin.php
- tests/behat/eula.feature
- tests/behat/forum.feature
- tests/behat/pseudo_submission.feature
- tests/behat/workshop.feature
This pull request makes improvements to the way users are handled within behat tests.
- The tests will first attempt to use an existing test account, otherwise create a new one.
- For the EULA test which requires a unique user the test will unenrol the user from Turnitin at the end of the test.
> Reuse user or unenrol if using unique user.

- lib.php
This fixes an issue where a student is able to open up Grademark before they should be able to - IE they don't yet have a grade/feedback.
> Disable Grademark for student if grade does not exist

- lib.php
This makes a change to the scenario where grades are released early for marking workflow and the post date is set to the current time, We need to set the post date to be in the past to avoid a race condition which means an error appears when the EV opens stating the grading service is not available.
> Marking workflow post date change - set to -5 minutes as opposed to current time

- amd/src/rubric.js
- classes/turnitin_view.class.php
- lib.php
Avoid relying on spying into hidden form fields to find course and/or course module ids, and instead declare data attributes on the element where the event handler is attached.
Refs #537.
> fix errors when displaying student rubric modal in any circumstance

- lib.php
when an activity does not use Turnitin, this causes 2 queries per user that is displayed on the page - so if we are showing 1000 users it results in 2000 db queries that aren't needed.
> Fix #591 - Cache activity settings correctly when disabled.

- lib.php
Hi,
This fixes the issue of incorrect grader as explained in https://github.com/turnitin/moodle-plagiarism_turnitin/issues/644
**Summary:**
The grader of the assignment is at times showing as the student or the system admin, when the assignment was actually graded by a teacher
**Steps to reproduce:**
- Create a new assignment by teacher role mod/assign/view.php?id=xyz
-- Display Similarity Reports to Students: Yes
- Login as the student and go to the assignment view page and submit assignment
- Wait for Turntin report to show percentage for plagiarism (by running cron twice ? and waiting)
- Login as teacher, go to assignment view page click on the percentage and go to Turntin
- Click on comments and grade section to enter grade and comments
- Close window
- Go go assignment view page, …
> Fix incorrect grader for mod_assign

- lib.php
If the file being checked is the special character `.`, then we should `continue;` before trying to read the file or even open a file handle.
> lib: skip fake files immediately

- classes/modules/turnitin_quiz.class.php
- tests/modules/turnitin_assign_test.php
- tests/modules/turnitin_forum_test.php
- tests/modules/turnitin_quiz_test.php
We were seeing PHPunit failures after installing this plugin into Moodle 4.3 (with PHP 8.2).
This is one way to fix it. May not be the most elegant, but I hope it is OK.
Among other things, this fixes issue #712.
I tested on Moodle 4.1 with PHP 7.4 to verify that I had not broken anything.
I hope this is helpful @carl-hostrander.
> Fix phpunit with Moodle 4.3 and PHP 8.2.

- classes/observer.php
- db/events.php
- lib.php
- version.php
This adds an observer to handle submission removal event, follow up the suggestion (number 2) by Tomo on
https://github.com/turnitin/moodle-plagiarism_turnitin/issues/556
Hi @jack-tii ,
Thanks for your note on:
https://github.com/turnitin/moodle-plagiarism_turnitin/pull/665
I have created another PR with a new branch in case (submission_removed_observer is being used)
The new branch has already rebased against 'develop'
> Submission removed observer

- lib.php
Addresses #515
Currently we are doing a whole load of unnecessary DB reads when running the cron job to send queued files to tii.
This PR does 2 things:
1. Fetch the coursemodule instance and module name upfront instead of in a loop. This eliminates the need to call get_coursemodule_from_id for each submission, removing 4 DB reads per submission.
2. Cache module settings up front - we only need one DB read per module for this, not one per submission. Therefore we can fetch them all in advance and read them from an array later.
> Optimising DB calls in cron

- vendor/Integrations/phpsdk-package/src/LTI.php
Resolves deprecation warnings under PHP 8.2
> Add missing properties for LTI.php

- lib.php
Currently we have a bug where if a student is assigned the role of teacher on a specific activity, they are unable to view TII report scores. This is because we are checking for teacher permissions at the course level only.
Resolves #608
> Check for capabilities at the activity level

- lib.php
Setting a file size upload limit over 100MiB will currently allow students to submit files which will break the submission queue. This adds a missing check to the submission process to skip the file if it's over the limit.
> Check file size when creating TII submission

- lib.php
This PR addresses 2 bugs which are preventing document viewer links from showing as they should.
Firstly, not all submissions that we want to be able to show similarity reports for have an associated grade item, therefore I removed the check that a grade item must always exist in order to display the link to the document viewer for a submission.
Secondly, the entire links area including both the document viewer link and submission status does not show up when an image is embedded in a forum submission. This is because the hash we are using as an identifier to look up the file does not match.
The identifier is initially created by hashing the entire submission content. However, when we look up the item later, any URLs in the submission contents will have been changed to use @@PLUGINFILE@@ …
> Fix DV links not showing in forums

- classes/hook_callbacks.php
- db/hooks.php
- lib.php
update_status was deprecated in Moodle 4.0 and will be removed completely in Moodle 4.5
This functionality was replaced in Moodle 4.0 by callback before_standard_top_of_body_html. In Moodle 4.4 it was replaced again, this time by the hooks API.
Since we presently support versions 4.1+, we have to support both approaches.
> Add before_standard_top_of_body_html hooks

- lib.php
This fixes a bug where courses are being created in TFS when the plugin is not enabled for an activity module within that course. This is inflating user counts and it's important for reporting that we get this patched.
The problem basically comes down to the fact that the PHP logic to create a course in TFS is wrapped up inside the logic that queries course data.
Previously when creating an activity module, loading the plugin settings form would make a call to get_course_data, which would then create the course in TFS. This meant that TFS courses could be erroneously created even without actually creating the Moodle activity module - just opening the settings and then backing out without saving was enough to trigger this behaviour.
I have removed this logic and replaced it with the …
> Don't create course when assignment settings page loaded

- lib.php
This PR removes the "(Moodle PP)" from the end of the assignment title in TFS. This is so that the assignment will have the same name in the LTI assignment copy tool as the name that the user sees within Moodle.
> Truncate assignment title in TFS

- settings.php
Previously this file was being loaded from jquery, now that we are on AMD for settings we need to load this separately.
> Fix css loading for datatables

- classes/turnitin_view.class.php
Currently if both the Plagiarism Plugin and Integrity Plugin are installed clicking the collapsing header in the settings menu for one of them will cause both to open. This is because both have the same name - 'plugin_header'. This PR changes the name of the header for this plugin so each name is unique and each settings menu can be opened separately.
> Change name of settings form headers

- lib.php
We should now be referring to the quiz_attempt class via the mod_quiz namespace. This namespace change was done in 3.9 so is valid in all versions we support.
> Add namespaces for mod_quiz

- classes/turnitin_view.class.php
2 of the report generation speed settings need to be swapped around to match up properly with TFS and allow collusion checks to happen as expected.
> Matching report generation speed settings

- lib.php
In Moodle 4.2 the PHP class quiz_attempt was moved out of the global namespace and into mod_quiz
Currently our plugin works for newer Moodle versions (4.2+) but we need to support Moodle 4.1. Therefore we need to add a check for the current Moodle version, and use the namespace version on Moodle 4.2+.
> Add version check for mod_quiz namespace

- lib.php
`print_error` is deprecated, we need to replace this by throwing a `moodle_exception`
> Replace print_error function

- lib.php
This adds backwards compatibility so that quiz attempts created using the old ID hash can still be used with the new plugin
> Using oldidentifier to query plagiarism_turnitin_files

- ajax.php
- classes/modules/turnitin_forum.class.php
- classes/turnitin_submission.class.php
- lib.php
Based on Moodle 4.5. TL;DR: This fixes the obvious faults preventing ideal-world resubmission from working, but matching HTML on the page to what's in the database is quite unlikely to work in reality.
I don't know how you easily reproduce the conditions of a Forum post submission fault in normal usage, but one possible way to fudge it if you've got successful submissions already is to insert `$plagiarismfile->statuscode = 'error';` beneath [this line](https://github.com/turnitin/moodle-plagiarism_turnitin/blob/9ed9c4ca81808e14bda530e133f567e94391096e/lib.php#L1011) to display the resubmit UI, and then observe in your browser the call made to `plagiarism/turnitin/ajax.php` when you click on resubmit elements.
Here's the reasoning behind the patch:
`forum_get_post_full()` is a function …
> resubmitting a forum post fails

- lib.php
For online text quiz attempts the hash lookup is failing as it's being calculated differently in `event_handler` vs `get_links`.
Also, hash collisions are possible when users upload the same text to two or more different quiz questions.
This PR adds a new hashing method that fixes both of these problems. We now calculate the hash for an online text quiz question attempt by concatenating the question type, the user id, the cmid, the slot, and the attempt id to create a unique string which is then hashed.
Example of generating a hash using the new method: `sha1(quiz_attempt user21 cm33 slot4 attempt1)`
This PR also adds a bit of extra logging for cron errors and implements looking submissions up by the previously generated hash to maintain backward compatibility.
> Quiz attempt hash updates

- lib.php
Looks like a typo in a previous PR, the `$queueditem->userid` refers to the uploader of a group submission, whereas `$userid` is 0 if it's a group submission.
> Using group userid for group text content

- classes/modules/turnitin_quiz.class.php
Fixes issue where grades do not sync back to the LMS after grading in TFS.
An update was made to the identifier calculation for quiz attempts. We need to also check for new style identifier hashes here, when updating the grade from TFS.
> Using new identifier calculation for quiz grading
